export const EMPLOYEE_BENEFIT_COST_PER_YEAR = 1000;
export const DEPENDENT_BENEFIT_COST_PER_YEAR = 500;
export const NAME_DISCOUNT_PERCENTAGE = 10;
export const EMPLOYEE_SALARY_PER_PAYCHECK = 2000;
export const NUMBER_OF_PAYCHECKS_PER_YEAR = 26;
